image: node:14
pipelines: 
  branches:    
    develop:      
      - step:
          caches:
            - node
          name: 'Building'
          script:  
            - export IMAGE_NAME=$DOCKER_USERNAME/$DOCKER_NAMESPACE:$BITBUCKET_COMMIT
            - export NAMESPACE=$DOCKER_NAMESPACE
            - docker build -t $IMAGE_NAME .
            - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - docker push $IMAGE_NAME
          services:
            - docker
      - step:
          name: Deploying
          script:
            - sed -i "s|navalbase/$DOCKER_NAMESPACE|$DOCKER_USERNAME/$DOCKER_NAMESPACE:$BITBUCKET_COMMIT|g" k8s/api-deployment.yaml      
            - pipe: atlassian/kubectl-run:1.3.4
              variables:
                KUBE_CONFIG: $KUBE_CONFIG
                KUBECTL_COMMAND: 'apply'
                KUBECTL_ARGS: 
                  - '--namespace=$DOCKER_NAMESPACE'
                RESOURCE_PATH: 'k8s/'