apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.image-pull-secret: dockerhub
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.image-pull-secret: dockerhub
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - image: navalbase/love-calculator-restapi-nestjs-typescript
        imagePullPolicy: ""
        name: api
        ports:
        - containerPort: 80
        resources: {}
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
